<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.coderych</groupId>
        <artifactId>server-commons</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>commons-mybatis-flex</artifactId>
    <description>数据库访问模块，基于 MyBatis-Flex 框架提供 ORM 和数据库操作支持</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.coderych</groupId>
            <artifactId>commons-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.coderych</groupId>
            <artifactId>commons-sa-token</artifactId>
        </dependency>
        <dependency>
            <groupId>com.coderych</groupId>
            <artifactId>commons-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-spring-boot4-starter</artifactId>
        </dependency>
    </dependencies>

</project>