<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.coderych</groupId>
        <artifactId>server</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>server-commons</artifactId>
    <packaging>pom</packaging>
    <description>通用组件模块集合，提供缓存、Web、安全、数据库等基础能力封装</description>
    <modules>
        <module>commons-all</module>
        <module>commons-core</module>
        <module>commons-web</module>
        <module>commons-test</module>
        <module>commons-cache</module>
        <module>commons-sa-token</module>
        <module>commons-mybatis-flex</module>
        <module>commons-log</module>
        <module>commons-oss</module>
        <module>commons-job</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-test</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-sa-token</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-mybatis-flex</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-log</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-oss</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.coderych</groupId>
                <artifactId>commons-job</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>